// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARM5i_f7e9GJ56jACXU2YhrNHynOm_Hbg',
    appId: '1:482063921592:web:833d37511e2f8fde6a1f4d',
    messagingSenderId: '482063921592',
    projectId: 'real-estate-app-88899',
    authDomain: 'real-estate-app-88899.firebaseapp.com',
    databaseURL: 'https://real-estate-app-88899-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'real-estate-app-88899.appspot.com',
    measurementId: 'G-7CNB5QPYSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvS0R_W67FyBRoCS8yFHmYTujYkPchHlI',
    appId: '1:482063921592:android:823ae92b09532e8b6a1f4d',
    messagingSenderId: '482063921592',
    projectId: 'real-estate-app-88899',
    databaseURL: 'https://real-estate-app-88899-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'real-estate-app-88899.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhzuSPnQ_pQy6SVWGEhW8lnrVmKGYmYZU',
    appId: '1:482063921592:ios:9db2279c086092c16a1f4d',
    messagingSenderId: '482063921592',
    projectId: 'real-estate-app-88899',
    databaseURL: 'https://real-estate-app-88899-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'real-estate-app-88899.appspot.com',
    iosClientId: '482063921592-ghptodqdq4msmdq35deeaqrftp56sdl2.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhzuSPnQ_pQy6SVWGEhW8lnrVmKGYmYZU',
    appId: '1:482063921592:ios:9db2279c086092c16a1f4d',
    messagingSenderId: '482063921592',
    projectId: 'real-estate-app-88899',
    databaseURL: 'https://real-estate-app-88899-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'real-estate-app-88899.appspot.com',
    iosClientId: '482063921592-ghptodqdq4msmdq35deeaqrftp56sdl2.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminProject',
  );
}
